version: '3.8'

# Development docker-compose with hot-reload
# Usage: docker-compose -f docker-compose.dev.yaml up

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: aexy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahul402
      POSTGRES_DB: aexy
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aexy-network

  # Backend Service (Development with hot-reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: aexy-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:rahul402@postgres:5432/aexy?schema=public
      JWT_SECRET: supersecretkey1234567890
      PORT: 5000
      NODE_ENV: development
      GEMINI_API_KEY: ${GEMINI_API_KEY:-AIzaSyC4FZKcWg2_bxNoLxvrUyGdTavp3rGAr2A}
      USE_REAL_AI: ${USE_REAL_AI:-false}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - aexy-network
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run dev"

  # Frontend Service (Development with hot-reload)
  frontend:
    image: node:22-alpine
    container_name: aexy-frontend
    restart: unless-stopped
    working_dir: /app
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_WS_URL: ws://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - aexy-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  aexy-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
